### ISSUE TITLE
core/getting-started.md is not up to date

### ISSUE THREAD

**Issue by yobrx** [api-platform/doc#50]
In GitHub documentation (`core/getting-started.md`), on branch `master`, routing is defined as following:

```yml
api:
    resource: '.'
    type:     'api'
    prefix:   '/api' # Optional
```

But, when I try, I get this error :
```
FileLoaderLoadException in Loader.php line 73:
Cannot load resource ".".
```

I fixed it by replacing : 
```yml
api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api' # Optional
```
